apiVersion: apps/v1
kind: Deployment
metadata:
  name: certman-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: certman-operator
  template:
    metadata:
      labels:
        name: certman-operator
    spec:
      serviceAccountName: certman-operator
      containers:
        - name: certman-operator
          image: quay.io/app-sre/certman-operator
          command:
          - certman-operator
          imagePullPolicy: Always
          resources:
            requests:
              memory: "150Mi"
              cpu: "10m"
            limits:
              memory: "300Mi"
              cpu: "30m"
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "certman-operator"
